SELECT T1.USER_ID, T1.PRODUCT_ID
FROM ONLINE_SALE T1
WHERE (T1.USER_ID, T1.PRODUCT_ID, T1.SALES_DATE) IN (
    SELECT USER_ID, PRODUCT_ID, MAX(SALES_DATE)
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
)
ORDER BY T1.USER_ID ASC, T1.PRODUCT_ID DESC;