-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, AGE, 
CASE 
    WHEN TLNO IS NOT NULL
    THEN TLNO 
    ELSE 'NONE' 
END AS TLNO
FROM PATIENT 
WHERE GEND_CD='W' AND CONVERT(AGE, SIGNED) <= 12
ORDER BY AGE DESC, PT_NAME ASC;